import "dotenv/config";
import Fastify from "fastify";
import cors from "@fastify/cors";
import fastifyStatic from "@fastify/static";
import fs from "fs";
import path from "path";

const port = Number(process.env.PORT) || 3000;
const host = "0.0.0.0";

const app = Fastify({
  logger: true,
});

const startedAt = new Date().toISOString();

const starterAssembly = {
  assemblyUid: "ASM-DEMO-0001",
  assetType: "VEHICLE",
  label: "Warranty-period vehicle assembly",
  status: "SEALED",
  currentCustodianId: "oem-demo-plant-04",
  currentLocationId: "oem-repairer-northgate",
  componentCount: 20,
  leafComponentCount: 12,
  hierarchyDepth: 5,
  anchoredSnapshot: {
    snapshotRef: "snap_demo_expected_0001",
    snapshotType: "INITIAL_SALE_CONFIGURATION",
    contentHash: "0x4d0f8a42b2fb2c92f6b3d3c9f0b7f09774f24116b9f25334f0b86a204de4fa91",
    targetLabel: "EVM dev target",
  },
  initialSaleBaseline: {
    soldAt: "2026-04-19T10:30:00.000Z",
    soldBy: "OEM plant 04",
    componentCount: 20,
    leafComponentCount: 12,
    purpose:
      "A sealed vehicle composition at first sale, used as the warranty-period baseline for later repair checks.",
  },
  expectedComponents: [
    {
      serial: "VIN-WVWZZZCD7NW184201",
      partNumber: "VEHICLE-RECORD",
      positionLabel: "vehicle",
      authenticatedBy: "H. Richter",
      repairerTier: "OEM manufacturing",
      networkStatus: "Inside OEM network",
    },
    {
      serial: "MTR-44721-A",
      partNumber: "MOTOR-AXL-44721",
      positionLabel: "front-drive-unit",
      authenticatedBy: "M. Kaur",
      repairerTier: "OEM repairer",
      networkStatus: "Inside approved repairer network",
    },
    {
      serial: "BAT-10291-K",
      partNumber: "BATTERY-MODULE-10291",
      positionLabel: "battery-module",
      authenticatedBy: "A. Walker",
      repairerTier: "OEM manufacturing",
      networkStatus: "Inside OEM network",
    },
    {
      serial: "ADAS-99015-R",
      partNumber: "SENSOR-ADAS-99015",
      positionLabel: "driver-assist-sensor",
      authenticatedBy: "Self-declared repair record",
      repairerTier: "Outside network",
      networkStatus: "Outside approved warranty network",
    },
  ],
};

const demoAssemblyTree = {
  assemblyUid: starterAssembly.assemblyUid,
  vin: "WVWZZZCD7NW184201",
  model: "ID.7 Pro S",
  schema: {
    rootKind: "VEHICLE",
    supportedNodeKinds: ["VEHICLE", "MAJOR_SYSTEM", "ASSEMBLY", "SUB_ASSEMBLY", "COMPONENT", "PART"],
    purpose:
      "Represent a complete car as a searchable aggregation tree until OEM schematics can be linked to the same nodes.",
  },
  root: {
    id: "veh-wvw184201",
    label: "WVWZZZCD7NW184201",
    nodeType: "Vehicle",
    category: "Complete vehicle",
    serial: "VIN-WVWZZZCD7NW184201",
    partNumber: "VEHICLE-RECORD",
    status: "OEM Authenticated",
    tone: "green",
    standard: "Initial-sale sealed vehicle composition",
    fittedBy: "OEM plant 04",
    repairerTier: "OEM manufacturing",
    networkStatus: "Inside OEM network",
    authenticatedBy: "H. Richter",
    authenticatorRole: "OEM release authority",
    warrantyImpact: "Primary aggregation baseline for the whole car.",
    recallExposure: "No vehicle-level campaign exposure.",
    anchorRef: "snap_demo_expected_0001",
    quantity: 1,
    children: [
      {
        id: "sys-powertrain",
        label: "Powertrain",
        nodeType: "Major system",
        category: "Engine and gearbox",
        status: "Verified",
        tone: "green",
        standard: "OEM powertrain specification",
        fittedBy: "OEM plant 04",
        repairerTier: "OEM manufacturing",
        networkStatus: "Inside OEM network",
        authenticatedBy: "A. Walker",
        authenticatorRole: "OEM component release",
        warrantyImpact: "Powertrain system is inside the initial-sale baseline.",
        recallExposure: "No open campaign exposure.",
        anchorRef: "snap_powertrain_184201",
        quantity: 1,
        children: [
          {
            id: "asm-engine",
            label: "Electric drive unit",
            nodeType: "Assembly",
            category: "Engine equivalent",
            serial: "MTR-44721-A",
            partNumber: "MOTOR-AXL-44721",
            status: "Approved Repairer",
            tone: "cyan",
            standard: "OEM replacement standard",
            fittedBy: "Northgate OEM Service",
            repairerTier: "OEM repairer",
            networkStatus: "Inside approved repairer network",
            authenticatedBy: "M. Kaur",
            authenticatorRole: "Approved repairer technician",
            warrantyImpact: "Replacement remains within OEM-supported repairer network.",
            recallExposure: "No open campaign exposure.",
            anchorRef: "snap_drive_unit_44721",
            quantity: 1,
            children: [
              {
                id: "sub-motor-stator",
                label: "Motor stator module",
                nodeType: "Sub-assembly",
                category: "Propulsion internals",
                serial: "STA-44721-01",
                partNumber: "MOTOR-STATOR-44721",
                status: "Verified",
                tone: "green",
                standard: "OEM standard",
                fittedBy: "OEM plant 04",
                repairerTier: "OEM manufacturing",
                networkStatus: "Inside OEM network",
                authenticatedBy: "A. Walker",
                authenticatorRole: "OEM component release",
                warrantyImpact: "Normal warranty evidence.",
                recallExposure: "No open campaign exposure.",
                anchorRef: "snap_stator_44721",
                quantity: 1,
              },
              {
                id: "part-inverter",
                label: "Inverter control module",
                nodeType: "Component",
                category: "Power electronics",
                serial: "INV-44721-09",
                partNumber: "INVERTER-CTRL-44721",
                status: "Verified",
                tone: "green",
                standard: "OEM standard",
                fittedBy: "OEM plant 04",
                repairerTier: "OEM manufacturing",
                networkStatus: "Inside OEM network",
                authenticatedBy: "N. Okafor",
                authenticatorRole: "OEM component release",
                warrantyImpact: "Supports powertrain warranty diagnostics.",
                recallExposure: "No open campaign exposure.",
                anchorRef: "snap_inverter_44721",
                quantity: 1,
              },
            ],
          },
          {
            id: "asm-gearbox",
            label: "Reduction gearbox",
            nodeType: "Assembly",
            category: "Gearbox",
            serial: "GBX-55819-F",
            partNumber: "GEARBOX-REDUCTION-55819",
            status: "Verified",
            tone: "green",
            standard: "OEM standard",
            fittedBy: "OEM plant 04",
            repairerTier: "OEM manufacturing",
            networkStatus: "Inside OEM network",
            authenticatedBy: "H. Richter",
            authenticatorRole: "OEM release authority",
            warrantyImpact: "Inside initial-sale baseline.",
            recallExposure: "No open campaign exposure.",
            anchorRef: "snap_gearbox_55819",
            quantity: 1,
          },
        ],
      },
      {
        id: "sys-chassis",
        label: "Suspension and braking",
        nodeType: "Major system",
        category: "Chassis",
        status: "Verified",
        tone: "green",
        standard: "OEM chassis specification",
        fittedBy: "OEM plant 04",
        repairerTier: "OEM manufacturing",
        networkStatus: "Inside OEM network",
        authenticatedBy: "A. Walker",
        authenticatorRole: "OEM component release",
        warrantyImpact: "No chassis exception recorded.",
        recallExposure: "No open campaign exposure.",
        anchorRef: "snap_chassis_184201",
        quantity: 1,
        children: [
          {
            id: "asm-front-suspension",
            label: "Front suspension module",
            nodeType: "Assembly",
            category: "Suspension",
            serial: "SUS-FRT-184201",
            partNumber: "SUSPENSION-FRONT-MODULE",
            status: "Verified",
            tone: "green",
            standard: "OEM standard",
            fittedBy: "OEM plant 04",
            repairerTier: "OEM manufacturing",
            networkStatus: "Inside OEM network",
            authenticatedBy: "A. Walker",
            authenticatorRole: "OEM component release",
            warrantyImpact: "Factory-fit evidence.",
            recallExposure: "No open campaign exposure.",
            anchorRef: "snap_front_suspension_184201",
            quantity: 1,
            children: [
              {
                id: "part-left-damper",
                label: "Left front damper",
                nodeType: "Component",
                category: "Suspension part",
                serial: "DMP-LF-88102",
                partNumber: "DAMPER-FRONT-LH",
                status: "Verified",
                tone: "green",
                standard: "OEM standard",
                fittedBy: "OEM plant 04",
                repairerTier: "OEM manufacturing",
                networkStatus: "Inside OEM network",
                authenticatedBy: "A. Walker",
                authenticatorRole: "OEM component release",
                warrantyImpact: "Factory-fit evidence.",
                recallExposure: "No open campaign exposure.",
                anchorRef: "snap_damper_lf_88102",
                quantity: 1,
              },
              {
                id: "part-wheel-speed",
                label: "Wheel speed sensor",
                nodeType: "Component",
                category: "Brake electronics",
                serial: "WSS-33019-LF",
                partNumber: "SENSOR-WHEEL-SPEED-LF",
                status: "Verified",
                tone: "green",
                standard: "OEM standard",
                fittedBy: "OEM plant 04",
                repairerTier: "OEM manufacturing",
                networkStatus: "Inside OEM network",
                authenticatedBy: "N. Okafor",
                authenticatorRole: "OEM component release",
                warrantyImpact: "Factory-fit evidence.",
                recallExposure: "No open campaign exposure.",
                anchorRef: "snap_wss_lf_33019",
                quantity: 1,
              },
            ],
          },
          {
            id: "asm-brake-system",
            label: "Brake system",
            nodeType: "Assembly",
            category: "Braking",
            serial: "BRK-184201-A",
            partNumber: "BRAKE-SYSTEM-184201",
            status: "Verified",
            tone: "green",
            standard: "OEM standard",
            fittedBy: "OEM plant 04",
            repairerTier: "OEM manufacturing",
            networkStatus: "Inside OEM network",
            authenticatedBy: "N. Okafor",
            authenticatorRole: "OEM component release",
            warrantyImpact: "Factory-fit evidence.",
            recallExposure: "No open campaign exposure.",
            anchorRef: "snap_brake_system_184201",
            quantity: 1,
          },
        ],
      },
      {
        id: "sys-body",
        label: "Bodywork and structure",
        nodeType: "Major system",
        category: "Body shell and panels",
        status: "Verified",
        tone: "green",
        standard: "OEM body specification",
        fittedBy: "OEM plant 04",
        repairerTier: "OEM manufacturing",
        networkStatus: "Inside OEM network",
        authenticatedBy: "H. Richter",
        authenticatorRole: "OEM release authority",
        warrantyImpact: "No structural exception recorded.",
        recallExposure: "No open campaign exposure.",
        anchorRef: "snap_body_184201",
        quantity: 1,
        children: [
          {
            id: "asm-body-shell",
            label: "Body shell",
            nodeType: "Assembly",
            category: "Structure",
            serial: "BODY-184201",
            partNumber: "BODY-SHELL-ID7",
            status: "Verified",
            tone: "green",
            standard: "OEM standard",
            fittedBy: "OEM plant 04",
            repairerTier: "OEM manufacturing",
            networkStatus: "Inside OEM network",
            authenticatedBy: "H. Richter",
            authenticatorRole: "OEM release authority",
            warrantyImpact: "Factory-fit evidence.",
            recallExposure: "No open campaign exposure.",
            anchorRef: "snap_body_shell_184201",
            quantity: 1,
          },
          {
            id: "part-front-bumper",
            label: "Front bumper cover",
            nodeType: "Component",
            category: "Exterior panel",
            serial: "BMP-FRT-77201",
            partNumber: "BUMPER-FRONT-ID7",
            status: "Part Replaced",
            tone: "steel",
            standard: "OEM replacement standard",
            fittedBy: "Northgate OEM Service",
            repairerTier: "OEM repairer",
            networkStatus: "Inside approved repairer network",
            authenticatedBy: "M. Kaur",
            authenticatorRole: "Approved repairer technician",
            warrantyImpact: "Replacement booked on with approved repair evidence.",
            recallExposure: "No open campaign exposure.",
            anchorRef: "snap_bumper_front_77201",
            quantity: 1,
          },
        ],
      },
      {
        id: "sys-interior",
        label: "Interior and safety",
        nodeType: "Major system",
        category: "Cabin and restraint systems",
        status: "Verified",
        tone: "green",
        standard: "OEM interior specification",
        fittedBy: "OEM plant 04",
        repairerTier: "OEM manufacturing",
        networkStatus: "Inside OEM network",
        authenticatedBy: "N. Okafor",
        authenticatorRole: "OEM component release",
        warrantyImpact: "No interior exception recorded.",
        recallExposure: "No open campaign exposure.",
        anchorRef: "snap_interior_184201",
        quantity: 1,
        children: [
          {
            id: "part-airbag-ecu",
            label: "Airbag ECU",
            nodeType: "Component",
            category: "Safety electronics",
            serial: "SRS-90112-C",
            partNumber: "CONTROL-AIRBAG-90112",
            status: "Verified",
            tone: "green",
            standard: "OEM standard",
            fittedBy: "OEM plant 04",
            repairerTier: "OEM manufacturing",
            networkStatus: "Inside OEM network",
            authenticatedBy: "N. Okafor",
            authenticatorRole: "OEM component release",
            warrantyImpact: "Factory-fit safety evidence.",
            recallExposure: "No open campaign exposure.",
            anchorRef: "snap_airbag_ecu_90112",
            quantity: 1,
          },
          {
            id: "asm-driver-seat",
            label: "Driver seat assembly",
            nodeType: "Assembly",
            category: "Interior",
            serial: "SEAT-D-30219",
            partNumber: "SEAT-DRIVER-ID7",
            status: "Verified",
            tone: "green",
            standard: "OEM standard",
            fittedBy: "OEM plant 04",
            repairerTier: "OEM manufacturing",
            networkStatus: "Inside OEM network",
            authenticatedBy: "A. Walker",
            authenticatorRole: "OEM component release",
            warrantyImpact: "Factory-fit evidence.",
            recallExposure: "No open campaign exposure.",
            anchorRef: "snap_driver_seat_30219",
            quantity: 1,
          },
        ],
      },
      {
        id: "sys-accessories",
        label: "Accessories and electronics",
        nodeType: "Major system",
        category: "Control, sensing, and convenience",
        status: "Warranty Review",
        tone: "amber",
        standard: "OEM electronics specification",
        fittedBy: "Mixed repair evidence",
        repairerTier: "Mixed",
        networkStatus: "One component outside approved warranty network",
        authenticatedBy: "Warranty operations",
        authenticatorRole: "OEM reviewer",
        warrantyImpact: "System contains a sensor fitment requiring warranty review.",
        recallExposure: "SC-ADAS-27F applies to affected ADAS serials.",
        anchorRef: "snap_accessories_184201",
        quantity: 1,
        children: [
          {
            id: "part-adas-sensor",
            label: "Driver assistance sensor",
            nodeType: "Component",
            category: "ADAS",
            serial: "ADAS-99015-R",
            partNumber: "SENSOR-ADAS-99015",
            status: "Warranty Review",
            tone: "amber",
            standard: "Aftermarket serial observed",
            fittedBy: "Independent workshop recorded",
            repairerTier: "Outside network",
            networkStatus: "Outside approved warranty network",
            authenticatedBy: "Self-declared repair record",
            authenticatorRole: "Non-network workshop",
            warrantyImpact: "OEM can see this ADAS part was fitted outside the repairer network.",
            recallExposure: "SC-ADAS-27F targets vehicles carrying affected ADAS sensor serials.",
            anchorRef: "snap_adas_sensor_99015",
            quantity: 1,
          },
          {
            id: "part-infotainment",
            label: "Infotainment head unit",
            nodeType: "Component",
            category: "Accessory electronics",
            serial: "INFO-77120-D",
            partNumber: "HEADUNIT-INFOTAINMENT-ID7",
            status: "Verified",
            tone: "green",
            standard: "OEM standard",
            fittedBy: "OEM plant 04",
            repairerTier: "OEM manufacturing",
            networkStatus: "Inside OEM network",
            authenticatedBy: "N. Okafor",
            authenticatorRole: "OEM component release",
            warrantyImpact: "Factory-fit evidence.",
            recallExposure: "No open campaign exposure.",
            anchorRef: "snap_infotainment_77120",
            quantity: 1,
          },
        ],
      },
    ],
  },
};

const demoRepairEvent = {
  repairEventId: "repair_demo_0001",
  assemblyUid: starterAssembly.assemblyUid,
  serviceOrderRef: "SO-WTY-184201-044",
  warrantyClaimRef: "WTY-ADAS-184201",
  reason: "ADAS calibration fault reported during warranty period",
  status: "WARRANTY_REVIEW",
  repairer: {
    name: "Northgate OEM Service",
    tier: "OEM repairer",
    networkStatus: "Inside approved repairer network",
  },
  openedBy: {
    displayName: "M. Kaur",
    role: "Approved repairer technician",
  },
  lifecycle: [
    {
      action: "VERIFY_PRESENT",
      positionLabel: "driver-assist-sensor",
      expectedSerial: "ADAS-99015-R",
      observedSerial: "ADAS-99015-R",
      networkStatus: "Inside approved repairer network",
      warrantyImpact: "None",
      authenticatedBy: "M. Kaur",
      notes: "Original sensor verified against the sealed initial-sale snapshot before removal.",
    },
    {
      action: "BOOK_OFF",
      positionLabel: "driver-assist-sensor",
      expectedSerial: "ADAS-99015-R",
      observedSerial: "ADAS-99015-R",
      networkStatus: "Inside approved repairer network",
      warrantyImpact: "None",
      authenticatedBy: "M. Kaur",
      notes: "Faulting sensor removed from vehicle assembly and retained against service order.",
    },
    {
      action: "BOOK_ON",
      positionLabel: "driver-assist-sensor",
      expectedSerial: "ADAS-99015-R",
      observedSerial: "ADAS-99177-X",
      networkStatus: "Outside approved warranty network",
      warrantyImpact: "Warranty review required",
      authenticatedBy: "Self-declared repair record",
      notes:
        "Replacement sensor serial is present on the car, but evidence shows the fitment originated outside the OEM repairer network.",
    },
  ],
};

const demoWarrantyWorkflows = {
  vin: "WVWZZZCD7NW184201",
  assemblyUid: starterAssembly.assemblyUid,
  serviceOrderRef: "SO-WTY-184201-044",
  warrantyClaimRef: "WTY-ADAS-184201",
  technician: {
    displayName: "M. Kaur",
    repairer: "Northgate OEM Service",
    repairerTier: "OEM repairer",
  },
  workflows: [
    {
      id: "original-part-confirmed",
      title: "Original part confirmed",
      tone: "green",
      assemblyNodeId: "part-adas-sensor",
      currentStatus: "Ready to book replacement",
      summary:
        "Technician scans the removed ADAS sensor and the serial matches the original sealed vehicle baseline.",
      expectedSerial: "ADAS-99015-R",
      scannedSerial: "ADAS-99015-R",
      replacementSerial: "ADAS-99177-OEM",
      partNumber: "SENSOR-ADAS-99015",
      scanOutcome: "ORIGINAL_MATCH",
      oemPartRecognised: true,
      shipmentTrace: {
        status: "Original factory fit",
        shippedTo: "OEM plant 04",
        repairerTier: "OEM manufacturing",
        networkStatus: "Inside OEM network",
      },
      warrantyImpact: "None",
      recommendedAction:
        "Book the faulty original part off the vehicle, book the authenticated replacement on, and retain repair evidence against the VIN file.",
      steps: [
        {
          label: "Open VIN file",
          detail: "Vehicle file WVWZZZCD7NW184201 is loaded with the sealed initial-sale assembly tree.",
          tone: "cyan",
        },
        {
          label: "Scan removed part",
          detail: "Removed part scan matches expected original serial ADAS-99015-R.",
          tone: "green",
        },
        {
          label: "Book off",
          detail: "Faulty original component is removed from Accessories and electronics / Driver assistance sensor.",
          tone: "cyan",
        },
        {
          label: "Book on",
          detail: "Replacement serial ADAS-99177-OEM is fitted and authenticated by an OEM repairer technician.",
          tone: "green",
        },
      ],
      evidenceLog: [
        "Original component confirmed against initial-sale snapshot.",
        "Faulty component booked off the vehicle assembly.",
        "Replacement component booked on with technician, repairer, and service order evidence.",
      ],
    },
    {
      id: "mismatch-investigation",
      title: "Mismatch investigation",
      tone: "amber",
      assemblyNodeId: "part-adas-sensor",
      currentStatus: "Warranty review required",
      summary:
        "Technician scans the removed ADAS sensor and the serial does not match the sealed original fitted part.",
      expectedSerial: "ADAS-99015-R",
      scannedSerial: "ADAS-44200-X",
      replacementSerial: "ADAS-99177-OEM",
      partNumber: "SENSOR-ADAS-99015",
      scanOutcome: "ORIGINAL_MISMATCH",
      oemPartRecognised: true,
      shipmentTrace: {
        status: "OEM serial recognised, but not original to this VIN",
        shippedTo: "West Quay Autocare",
        repairerTier: "Outside network",
        networkStatus: "Outside approved warranty network",
      },
      warrantyImpact: "Warranty risk",
      recommendedAction:
        "Flag mismatch, show OEM part/shipment trace, book the unexpected component off, fit an authenticated replacement, and route the claim to warranty review.",
      steps: [
        {
          label: "Open VIN file",
          detail: "Vehicle file shows ADAS-99015-R as the sealed original component.",
          tone: "cyan",
        },
        {
          label: "Scan removed part",
          detail: "Removed component ADAS-44200-X does not match the original vehicle baseline.",
          tone: "amber",
        },
        {
          label: "Trace part",
          detail: "Serial is recognised as OEM, but shipment trace points to an outside-network workshop.",
          tone: "red",
        },
        {
          label: "Warranty route",
          detail: "Technician can still book the work, but the warranty claim is marked for OEM review.",
          tone: "amber",
        },
      ],
      evidenceLog: [
        "Mismatch recorded against sealed initial-sale snapshot.",
        "Scanned part recognised as an OEM serial.",
        "Shipment trace shows outside-network destination, creating potential warranty invalidation.",
      ],
    },
  ],
};

const demoRecallCampaign = {
  campaignCode: "SC-ADAS-27F",
  title: "ADAS sensor water ingress safety campaign",
  severity: "SAFETY_RECALL",
  status: "ACTIVE",
  target: {
    partNumber: "SENSOR-ADAS-99015",
    serialPrefix: "ADAS-99",
    rule: "Target vehicles currently carrying affected ADAS sensor serials.",
  },
  focusedExposure: {
    assemblyUid: starterAssembly.assemblyUid,
    vin: "WVWZZZCD7NW184201",
    componentSerial: "ADAS-99015-R",
    exposureStatus: "REPAIR_BOOKED",
    reason: "Affected component is attached to this vehicle assembly.",
    action:
      "Book the affected component off the car, fit an authenticated replacement, then clear the campaign exposure.",
  },
  buyerCareSignal: {
    label: "Care history evidence",
    summary:
      "Future buyers can see that a recall-sensitive component was identified, removed, replaced, and authenticated instead of relying on a generic service stamp.",
  },
};

async function main() {
  await app.register(cors, {
    origin: true,
  });

  app.get("/health", async () => ({
    status: "ok",
    app: "VINtegrity",
    company: "AuthLine Auto",
    parentCompany: "AuthLine",
    startedAt,
  }));

  app.get("/api/v1/meta", async () => ({
    company: {
      name: "AuthLine Auto",
      parentCompany: "AuthLine",
      description: "The automotive industry arm of AuthLine.",
    },
    product: {
      name: "VINtegrity",
      tagline: "OEM warranty intelligence for authenticated vehicle assemblies by AuthLine Auto.",
    },
    status: "starter",
    capabilities: [
      "Vehicle assembly aggregation",
      "Searchable multi-level assembly directory",
      "Initial-sale vehicle composition baseline",
      "Nested major systems, assemblies, sub-assemblies, components, and parts",
      "Serialized component authentication by named users",
      "Book-off and book-on repair event lifecycle",
      "Technician scan evidence for removed parts",
      "Original-part mismatch detection against sealed VIN baseline",
      "OEM part recognition and shipment trace for warranty review",
      "OEM and approved repairer network evidence",
      "Tiered repairer model for warranty review",
      "Targeted recall exposure by component-to-vehicle attachment",
      "Outside-network fitment detection",
      "Warranty impact triage against authenticated parts",
      "Vehicle care history for future buyer confidence",
      "Auditable repair and fitment event trail",
    ],
    suggestedNextBuildSteps: [
      "Register serialized OEM components",
      "Create vehicle assemblies and sub-assemblies",
      "Build each vehicle as a searchable aggregation tree",
      "Seal the initial sale composition for each vehicle",
      "Authenticate component fitments by user and repairer tier",
      "Book components off and back on during repair work",
      "Scan removed parts and compare against the original VIN baseline",
      "Trace mismatched OEM parts to shipment destination and repairer network tier",
      "Resolve safety campaigns to vehicles carrying affected components",
      "Record repairs from OEM, approved, tier 2, and outside-network repairers",
      "Detect warranty-sensitive parts fitted outside the repairer network",
      "Present warranty impact evidence to OEM review teams",
    ],
    anchorTargets: [
      { targetKey: "evm-dev", label: "EVM dev target", kind: "EVM", enabled: true, primary: true },
      { targetKey: "solana-dev", label: "Solana dev target", kind: "SOLANA", enabled: false, primary: false },
    ],
  }));

  app.get("/api/v1/assemblies/demo", async () => starterAssembly);

  app.get("/api/v1/assemblies/demo/tree", async () => demoAssemblyTree);

  app.get("/api/v1/repair-events/demo", async () => demoRepairEvent);

  app.get("/api/v1/warranty-workflows/demo", async () => demoWarrantyWorkflows);

  app.get("/api/v1/recalls/demo", async () => demoRecallCampaign);

  app.get("/api/v1/inspections/demo", async () => ({
    inspectionId: "insp_demo_0001",
    assemblyUid: starterAssembly.assemblyUid,
    result: "MISMATCH",
    summary: "One fitted driver assistance sensor differs from the trusted vehicle assembly snapshot and needs OEM warranty review.",
    observations: [
      { positionLabel: "vehicle", observedSerial: "VIN-WVWZZZCD7NW184201", matched: true },
      { positionLabel: "front-drive-unit", observedSerial: "MTR-44721-A", matched: true },
      { positionLabel: "battery-module", observedSerial: "BAT-10291-K", matched: true },
      {
        positionLabel: "driver-assist-sensor",
        observedSerial: "ADAS-99177-X",
        matched: false,
        varianceReason: "Observed component was fitted outside the approved repairer network",
      },
    ],
  }));

  const frontendDist = path.resolve(process.cwd(), "../frontend/dist");
  if (fs.existsSync(frontendDist)) {
    await app.register(fastifyStatic, {
      root: frontendDist,
      prefix: "/",
      wildcard: false,
    });
  }

  app.setNotFoundHandler(async (request, reply) => {
    if (request.raw.url?.startsWith("/api/")) {
      return reply.code(404).send({ error: "Not found" });
    }

    const indexPath = path.join(frontendDist, "index.html");
    if (fs.existsSync(indexPath)) {
      return reply.type("text/html").send(fs.readFileSync(indexPath, "utf8"));
    }

    return reply.code(404).send("VINtegrity starter is running, but the frontend bundle has not been built yet.");
  });

  await app.listen({ port, host });
}

main().catch((error) => {
  app.log.error(error);
  process.exit(1);
});
